env:
  node: true
  es6: true
  mocha: true

rules:
  no-var: 2
  no-console: 0
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
extends: eslint:recommended

plugins: [ejs]
